baseurl: /morgantown
permalink: pretty
markdown: kramdown
paginate: 5
repo: starter
github_org: maptime
maptime:
  chapter: Maptime Morgantown
  twitter: MaptimeMGWV
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
